from setuptools import setup

setup(
    name='googleDrive',
    version='1.0',
    packages=['venv.lib.python3.6.site-packages.rsa', 'venv.lib.python3.6.site-packages.lxml',
              'venv.lib.python3.6.site-packages.lxml.html', 'venv.lib.python3.6.site-packages.lxml.includes',
              'venv.lib.python3.6.site-packages.lxml.isoschematron', 'venv.lib.python3.6.site-packages.xlsx',
              'venv.lib.python3.6.site-packages.jaraco.classes', 'venv.lib.python3.6.site-packages.pyasn1',
              'venv.lib.python3.6.site-packages.pyasn1.type', 'venv.lib.python3.6.site-packages.pyasn1.codec',
              'venv.lib.python3.6.site-packages.pyasn1.codec.ber', 'venv.lib.python3.6.site-packages.pyasn1.codec.cer',
              'venv.lib.python3.6.site-packages.pyasn1.codec.der',
              'venv.lib.python3.6.site-packages.pyasn1.codec.native', 'venv.lib.python3.6.site-packages.pyasn1.compat',
              'venv.lib.python3.6.site-packages.samples', 'venv.lib.python3.6.site-packages.samples.dns_sample',
              'venv.lib.python3.6.site-packages.samples.dns_sample.dns_v1',
              'venv.lib.python3.6.site-packages.samples.iam_sample',
              'venv.lib.python3.6.site-packages.samples.iam_sample.iam_v1',
              'venv.lib.python3.6.site-packages.samples.fusiontables_sample',
              'venv.lib.python3.6.site-packages.samples.fusiontables_sample.fusiontables_v1',
              'venv.lib.python3.6.site-packages.samples.servicemanagement_sample',
              'venv.lib.python3.6.site-packages.samples.servicemanagement_sample.servicemanagement_v1',
              'venv.lib.python3.6.site-packages.apitools', 'venv.lib.python3.6.site-packages.apitools.gen',
              'venv.lib.python3.6.site-packages.apitools.base', 'venv.lib.python3.6.site-packages.apitools.base.py',
              'venv.lib.python3.6.site-packages.apitools.base.py.testing',
              'venv.lib.python3.6.site-packages.apitools.base.protorpclite',
              'venv.lib.python3.6.site-packages.apitools.data', 'venv.lib.python3.6.site-packages.apitools.scripts',
              'venv.lib.python3.6.site-packages.httplib2', 'venv.lib.python3.6.site-packages.openpack',
              'venv.lib.python3.6.site-packages.apiclient', 'venv.lib.python3.6.site-packages.fasteners',
              'venv.lib.python3.6.site-packages.fasteners.tests', 'venv.lib.python3.6.site-packages.uritemplate',
              'venv.lib.python3.6.site-packages.google_drive', 'venv.lib.python3.6.site-packages.oauth2client',
              'venv.lib.python3.6.site-packages.oauth2client.contrib',
              'venv.lib.python3.6.site-packages.oauth2client.contrib.django_util',
              'venv.lib.python3.6.site-packages.more_itertools',
              'venv.lib.python3.6.site-packages.more_itertools.tests',
              'venv.lib.python3.6.site-packages.pyasn1_modules', 'venv.lib.python3.6.site-packages.googleapiclient',
              'venv.lib.python3.6.site-packages.googleapiclient.discovery_cache',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.req',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.vcs',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.utils',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.compat',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.models',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.commands',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.operations'],
    url='',
    license='Google',
    author='albert',
    author_email='albert.kulinski@hotmail.com',
    description='Program kontrolujący zapisy'
)
